Repository The-Strategy-Unit/nhp_outputs, pull requests merged in 2025-03, with the labels that each got.

#293 Interpret and display data from updated NDG json structure
  R/mod_info_params.R
  R/mod_info_params_fct_tables.R
  inst/sample_params.json
  tests/testthat/_snaps/mod_info_params.md
Labels: bug, must

#291 updates actions to deploy to new production server
  .github/workflows/connect-publish-dev.yaml
  .github/workflows/connect-publish-manual.yaml
  .github/workflows/connect-publish-prod.yaml
Labels: enhancement, should

#295 Add NDG variant and value type to params report download
  R/fct_report.R
Labels: enhancement, must

#296 Fix deploy action
  .github/workflows/connect-publish-manual.yaml
Labels: bug, must

#297 fixes action: used wrong variable name (typo)
  .github/workflows/connect-publish-prod.yaml
Labels: bug, must
