Repository The-Strategy-Unit/nhp_outputs, pull requests merged in 2025-06, with the labels that each got.

#316 Deploy to both servers
  deploy.R
Labels: enhancement, must

#315 adds caching for the result set metadata
  app.R
Labels: enhancement, could

#318 Bump to v3.6.0
  DESCRIPTION
Labels: documentation, must

#320 Skip `tribble()` reformatting
  .Rbuildignore
  air.toml
  tests/testthat/test-fct_get_data.R
  tests/testthat/test-fct_gt_theme.R
  tests/testthat/test-mod_info_downloads.R
  tests/testthat/test-mod_info_home.R
  tests/testthat/test-mod_measure_selection.R
  tests/testthat/test-mod_model_core_activity.R
  tests/testthat/test-mod_model_results_distribution.R
  tests/testthat/test-mod_principal_change_factor_effects.R
  tests/testthat/test-mod_principal_detailed.R
  tests/testthat/test-mod_principal_summary.R
  tests/testthat/test-mod_principal_summary_los.R
Labels: enhancement, should

#324 Rename tretspef-related objects and variables
  R/fct_get_data.R
  R/mod_principal_detailed.R
  R/mod_principal_summary_los.R
  inst/app/data/excel_dictionary.json
  tests/testthat/test-fct_get_data.R
  tests/testthat/test-mod_principal_detailed.R
  tests/testthat/test-mod_principal_summary_los.R
Labels: enhancement, must
