Repository The-Strategy-Unit/nhp_outputs, pull requests merged in 2025-09, with the labels that each got.

#339 Bump to v4.1
  DESCRIPTION
Labels: documentation, must

#341 Remove covid adjustment remnants form interface/reports
  R/fct_report.R
  R/mod_info_params.R
  R/mod_info_params_fct_tables.R
  tests/testthat/_snaps/mod_info_params.md
  tests/testthat/_snaps/mod_info_params_fct_tables.md
  tests/testthat/test-mod_info_params.R
  tests/testthat/test-mod_info_params_fct_tables.R
Labels: enhancement, must

#343 adds icbs to datasets
  app.R
  datasets.json
  providers.Rds
  providers.json
Labels: enhancement, should
